name: Gitlab Community
description: |
  Gitlab CE is a free GitHub alternative
version: latest
category: Versioning
maintainer: "Sebastien Langoureaux <linuxworkgroup@gmail.com>"
license: MIT License 
projectURL: https://gitlab.com/gitlab-org/gitlab-ce
