name: GoCD
description: |
  GoCD Stack (server and agents)
version: 17.7.0-rancher1
category: Continuous Integration
maintainer: "Sebastien Langoureaux <linuxworkgroup@gmail.com>"
license: Apache License
projectURL: https://www.gocd.io/
